"""changed the Announcement table added column total comments

Revision ID: 97d89d5910e4
Revises: 9e6ce74983df
Create Date: 2023-07-27 13:28:03.614719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d89d5910e4'
down_revision = '9e6ce74983df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('total_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'total_comments')
    # ### end Alembic commands ###
