"""changed comment table

Revision ID: 9e6ce74983df
Revises: ab6eef00dcc8
Create Date: 2023-07-27 01:06:21.078560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6ce74983df'
down_revision = 'ab6eef00dcc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.VARCHAR(), nullable=True))
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
