"""added on table announcements the column updated at

Revision ID: ab6eef00dcc8
Revises: da96b3b164be
Create Date: 2023-07-27 00:49:06.436508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6eef00dcc8'
down_revision = 'da96b3b164be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'updated_at')
    # ### end Alembic commands ###
