"""added on table announcements the column updated at

Revision ID: da96b3b164be
Revises: 6c552039bfa4
Create Date: 2023-07-27 00:40:29.089003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da96b3b164be'
down_revision = '6c552039bfa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
